#ifndef __ITEMS_H__
#define __ITEMS_H__

enum Items
{
	XENORITE_ORE = 0,
	XENORITE_BAR = 1,
	KRONOMITE_ORE = 2,
	KRONOMITE_BAR = 3,
	RAW_CRYSTALITE = 4,
	REFINED_CRYSTALITE = 5,
	ROCK = 6,
	HARDENED_ROCK = 7,
	BASIC_FURNACE = 8,
	CRUDE_CRAFTER = 9,
	CRUDE_GENERATOR = 10,
	CIRCUT = 11,
	RESEARCH_INGREDIENTS = 12,
	RESEARCH_CENTER = 13,
}

#endif

